


# Visualise Tajima's D, pi, and Fst for AM pop2 and pop5 (MSL0 vs MSL4) on chr31
# Data generated by: population_statistics_and_fst2.R (50kb windows, 1kb Fst windows)




# 1. SETUP ---------------------------------------------------------------------

library(tidyverse)
library(patchwork)

# Colours (Paul Tol colour-blind palette)
col_msl0 <- "#BB5566"  # Rose/red — MSL0 (deletion present)
col_msl4 <- "#004488"  # Dark blue — MSL4 (deletion absent)

# Base directory — change if needed
base_dir <- "/home/johansson/Documents/Bioinformatics/Leishmania/Leishmania Manuscript"
data_dir <- file.path(base_dir, "Data/Population Diversity and Differentiation")
fig_dir  <- file.path(base_dir, "Figures/Population Diversity and Differentiation")
dir.create(fig_dir, showWarnings = FALSE, recursive = TRUE)

# MSL locus coordinates on chr31 (from MSL-genes-only.bed)
msl_start <- 1181282
msl_end   <- 1192406




# 2. LOAD DATA -----------------------------------------------------------------

# Helper function to load pi files
load_pi <- function(path, pop, msl) {
  read_tsv(path, show_col_types = FALSE) %>%
    mutate(
      midpoint = (BIN_START + BIN_END) / 2,
      population = pop,
      msl_group = msl
    )
}

# Helper function to load Tajima's D files
load_tajd <- function(path, pop, msl) {
  read_tsv(path, show_col_types = FALSE) %>%
    mutate(
      midpoint = BIN_START + 25000,  # 50kb window midpoint
      population = pop,
      msl_group = msl
    ) %>%
    filter(!is.nan(TajimaD))
}

# Helper function to load Fst files
load_fst <- function(path, pop) {
  read_tsv(path, show_col_types = FALSE) %>%
    mutate(
      midpoint = (BIN_START + BIN_END) / 2,
      population = pop
    ) %>%
    filter(!is.nan(WEIGHTED_FST), WEIGHTED_FST >= 0)
}

# Pi files
pi_pop2_msl0 <- load_pi(
  file.path(data_dir, "pop_2__Americas.K13.pop2.MSL0.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.windowed.pi"),
  "Pop2", "MSL0"
)
pi_pop2_msl4 <- load_pi(
  file.path(data_dir, "pop_15__Americas.K13.pop2.MSL4.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.windowed.pi"),
  "Pop2", "MSL4"
)
pi_pop5_msl0 <- load_pi(
  file.path(data_dir, "pop_5__Americas.K13.pop5.MSL0.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.windowed.pi"),
  "Pop5", "MSL0"
)
pi_pop5_msl4 <- load_pi(
  file.path(data_dir, "pop_18__Americas.K13.pop5.MSL4.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.windowed.pi"),
  "Pop5", "MSL4"
)

# Tajima's D files
tajd_pop2_msl0 <- load_tajd(
  file.path(data_dir, "pop_2__Americas.K13.pop2.MSL0.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.Tajima.D"),
  "Pop2", "MSL0"
)
tajd_pop2_msl4 <- load_tajd(
  file.path(data_dir, "pop_15__Americas.K13.pop2.MSL4.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.Tajima.D"),
  "Pop2", "MSL4"
)
tajd_pop5_msl0 <- load_tajd(
  file.path(data_dir, "pop_5__Americas.K13.pop5.MSL0.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.Tajima.D"),
  "Pop5", "MSL0"
)
tajd_pop5_msl4 <- load_tajd(
  file.path(data_dir, "pop_18__Americas.K13.pop5.MSL4.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.Tajima.D"),
  "Pop5", "MSL4"
)

# Fst files
fst_pop2 <- load_fst(
  file.path(data_dir, "fst_2__Americas.K13.pop2.MSL0.diploidised.sample_names.txt__Americas.K13.pop2.MSL4.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.windowed.weir.fst"),
  "Pop2"
)
fst_pop5 <- load_fst(
  file.path(data_dir, "fst_5__Americas.K13.pop5.MSL0.diploidised.sample_names.txt__Americas.K13.pop5.MSL4.diploidised.sample_names.txt__tetraploid_freebayes_regenotyped_sorted_LinJ.31_2025-07-01.filtered_2026-04-07.diploidised.vcf.gz.windowed.weir.fst"),
  "Pop5"
)

# Combine
pi_pop2   <- bind_rows(pi_pop2_msl0, pi_pop2_msl4)
pi_pop5   <- bind_rows(pi_pop5_msl0, pi_pop5_msl4)
tajd_pop2 <- bind_rows(tajd_pop2_msl0, tajd_pop2_msl4)
tajd_pop5 <- bind_rows(tajd_pop5_msl0, tajd_pop5_msl4)




# 3. SHARED THEME --------------------------------------------------------------

theme_pop <- function() {
  theme_bw() +
    theme(
      panel.grid.minor   = element_blank(),
      panel.grid.major.x = element_blank(),
      axis.text          = element_text(size = 11),
      axis.title         = element_text(size = 12),
      legend.title       = element_text(size = 12, face = "bold"),
      legend.text        = element_text(size = 11),
      legend.position    = "right",
      plot.title         = element_text(size = 13, face = "bold", hjust = 0.5),
      plot.title.position = "plot",
      strip.text         = element_text(size = 11)
    )
}

# MSL locus shading layer — widened to 100kb either side for visibility at chr31 scale
msl_shade <- annotate(
  "rect",
  xmin = msl_start - 100000, xmax = msl_end + 100000,
  ymin = -Inf, ymax = Inf,
  fill = "#CCCCCC", alpha = 0.4
)

# Colour scale
msl_colours <- scale_colour_manual(
  name   = "MSL group",
  values = c("MSL0" = col_msl0, "MSL4" = col_msl4),
  labels = c("MSL0 (deletion present)", "MSL4 (deletion absent)")
)




# 4. PLOTTING FUNCTION ---------------------------------------------------------

make_figure <- function(tajd_data, pi_data, fst_data, pop_label, pop_note) {
  
  x_lab <- "Position on chr31 (bp)"
  
  # Tajima's D panel
  p_tajd <- ggplot(tajd_data, aes(x = midpoint, y = TajimaD, colour = msl_group)) +
    msl_shade +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey50", linewidth = 0.4) +
    geom_line(linewidth = 0.7, alpha = 0.85) +
    geom_point(size = 1.5, alpha = 0.7) +
    msl_colours +
    labs(
      title = paste0(pop_label, " — Tajima's D across chr31\n", pop_note),
      x = NULL,
      y = "Tajima's D"
    ) +
    theme_pop()
  
  # Pi panel
  p_pi <- ggplot(pi_data, aes(x = midpoint, y = PI, colour = msl_group)) +
    msl_shade +
    geom_line(linewidth = 0.7, alpha = 0.85) +
    geom_point(size = 1.5, alpha = 0.7) +
    msl_colours +
    labs(
      x = NULL,
      y = expression(paste("Nucleotide diversity (", pi, ")"))
    ) +
    theme_pop()
  
  # Fst panel — loess smoothed only (1kb raw windows too noisy to plot)
  p_fst <- ggplot(fst_data, aes(x = midpoint, y = WEIGHTED_FST)) +
    msl_shade +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey50", linewidth = 0.4) +
    geom_smooth(method = "loess", span = 0.15, se = TRUE,
                colour = "#CC3311", fill = "#CC3311", alpha = 0.15, linewidth = 0.9) +
    labs(
      x = x_lab,
      y = expression(F[ST])
    ) +
    theme_pop()
  
  # Combine with patchwork
  p_tajd / p_pi / p_fst +
    plot_layout(heights = c(1.2, 1, 0.8), guides = "collect") &
    theme(legend.position = "right")
}




# 5. BUILD FIGURES -------------------------------------------------------------

fig_pop2 <- make_figure(
  tajd_data  = tajd_pop2,
  pi_data    = pi_pop2,
  fst_data   = fst_pop2,
  pop_label  = "AM Population 2 (MSL0 n=24, MSL4 n=46)",
  pop_note   = "50kb windows | Grey shading = MSL locus ±100kb (chr31: 1,181,282–1,192,406)"
)

fig_pop5 <- make_figure(
  tajd_data  = tajd_pop5,
  pi_data    = pi_pop5,
  fst_data   = fst_pop5,
  pop_label  = "AM Population 5 (MSL0 n=18, MSL4 n=2)",
  pop_note   = "50kb windows | Grey shading = MSL locus ±100kb | CAVEAT: MSL4 n=2"
)




# 6. SAVE FIGURES --------------------------------------------------------------

ggsave(
  filename = file.path(fig_dir, "pop2_tajd_pi_fst_chr31.jpeg"),
  plot     = fig_pop2,
  width    = 12, height = 14, dpi = 300
)

ggsave(
  filename = file.path(fig_dir, "pop2_tajd_pi_fst_chr31.pdf"),
  plot     = fig_pop2,
  width    = 12, height = 14
)

ggsave(
  filename = file.path(fig_dir, "pop5_tajd_pi_fst_chr31.jpeg"),
  plot     = fig_pop5,
  width    = 12, height = 14, dpi = 300
)

ggsave(
  filename = file.path(fig_dir, "pop5_tajd_pi_fst_chr31.pdf"),
  plot     = fig_pop5,
  width    = 12, height = 14
)

message("Figures saved to: ", fig_dir)



